### ISSUE TITLE
[PE-D][Tester A] Error message inconsistent with UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F11-2/tp#207] opened 2023-11-03 21:29 UTC
The error messages are inconsistent with the one provided in UG. 

Expected: edit command should started with "guest edit ..." or "vendor edit ..."
Actual: edit command could start with "edit ..."

below are screenshots of the bug:

![Screenshot 2023-11-03 at 5.04.18 PM.png](https://raw.githubusercontent.com/KamJiaYue/ped/main/files/412f855d-480d-45aa-b390-0bed6de2b228.png)

![Screenshot 2023-11-03 at 5.04.24 PM.png](https://raw.githubusercontent.com/KamJiaYue/ped/main/files/9c44b345-95b2-45eb-8294-5dd45f26ca8e.png)

![Screenshot 2023-11-03 at 5.04.31 PM.png](https://raw.githubusercontent.com/KamJiaYue/ped/main/files/2f26192c-a25b-45b5-934a-e022ebf20a3a.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: KamJiaYue/ped#3

**Comment by wasjoe1** [comment] 2023-11-06 04:11
3) edit error command ⇒ we should just make it such that “edit” commands return "unknown command" message like other commands and not try to handle it

**Comment by p-xp** [comment] 2023-11-06 06:12
Closed as duplicate of #211. Will be resolved when edit feature is removed in #113.

**Closed** 2023-11-06 06:12 UTC
